// src/components/Button.vue
<template>
  <button
    :type="type"
    class="text-grey-darkest font-bold py-2 px-4 rounded inline-flex items-center focus:outline-none text-grey-lightest"
    :class="colorClass + ' ' + widthClasses"
    @click="$emit('onClick')"
  >
    <font-awesome-icon v-if="icon" class="mr-2" :icon="icon" />
    <span>{{ text }}</span>
  </button>
</template>

<script>
export default {
  props: {
    type: String,
    text: String,
    color: String,
    icon: String,
    fullWidth: Boolean
  },
  computed: {
    colorClass() {
      if (this.color) {
        return `bg-${this.color} hover:bg-${this.color}-dark`
      } else {
        return 'bg-grey hover:bg-grey-dark'
      }
    },
    widthClasses() {
      if (this.fullWidth) {
        return 'w-full justify-center'
      } else {
        return ''
      }
    }
  }
}
</script>

// src/components/Button/Button.svelte
<script>
  export let label = '';
  export let fullWidth = false;
  export let type = 'button';
</script>

<button
  {type}
  on:click
  class:w-full={fullWidth}
  class="bg-teal-500 hover:bg-teal-400 text-white font-bold py-2 px-4 border-b-4
  border-teal-700 hover:border-teal-500 rounded">
  {label}
</button>
