// src/components/Textarea.svelte
<script>
  export let label = '';
  export let value = '';
  export let name = '';
  export let isFormField = false;
  export let rows = 5;
</script>

<div class="flex flex-col">
  <label class="block text-gray-600 font-bold mb-1 uppercase text-sm">
    {label}
  </label>
  <textarea
    class="bg-gray-300 appearance-none border-2 border-gray-300 rounded w-full
    py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white
    focus:border-blue-500"
    {name}
    class:mb-8={isFormField}
    {value}
    on:change
    {rows} />
</div>

// src/components/TextArea/index.vue
<template>
  <div>
    <label
      class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2"
      v-if="label"
    >
      {{ label }}
    </label>
    <textarea
      :name="name"
      :id="id"
      rows="5"
      :placeholder="placeholder"
      @input="$emit('input', $event.target.value)"
      class="appearance-none block w-full bg-white text-grey-darker border-2 rounded py-3 px-4 mb-1 leading-tight focus:outline-none rounded"
      :class="hasErrors ? 'border-2 border-red-light' : ''"
    />
    <span class="text-sm text-red-light" v-if="errorMessage">{{
      errorMessage
    }}</span>
  </div>
</template>

<script>
export default {
  props: {
    label: String,
    name: String,
    id: String,
    placeholder: String,
    hasErrors: Boolean,
    errorMessage: String
  },
  $_veeValidate: {
    value() {
      return this.$el.value
    },
    name() {
      return this.name
    }
  }
}
</script>
