// src/components/TextArea.vue
<template>
  <div>
    <label
      class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2"
      v-if="label"
    >
      {{ label }}
    </label>
    <textarea
      :name="name"
      :id="id"
      rows="4"
      :placeholder="placeholder"
      @input="$emit('input', $event.target.value)"
      class="appearance-none block w-full bg-white text-grey-darker border-2 rounded py-3 px-4 mb-1 leading-tight focus:outline-none"
      :class="hasErrors ? 'border-2 border-red-light' : ''"
    />
    <span class="text-sm text-red-light" v-if="errorMessage">{{
      errorMessage
    }}</span>
  </div>
</template>

<script>
export default {
  props: {
    label: String,
    name: String,
    id: String,
    placeholder: String,
    hasErrors: Boolean,
    errorMessage: String
  },
  $_veeValidate: {
    value() {
      return this.$el.value
    },
    name() {
      return this.name
    }
  }
}
</script>

// src/components/Textarea/Textarea.svelte
<script>
  export let label = undefined;
  export let id = undefined;
  export let value = '';
  export let name = '';
  export let isFormField = false;
  export let fullWidth = false;
  export let placeholder = '';
  export let required = false;
  export let hasError = false;
  export let rows = 4;

  $: classes =
    'bg-white appearance-none border-2 border-gray-300 rounded w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:border-teal-500 ' +
    ($$props.class ? $$props.class : '');
</script>

<div class:w-full={fullWidth} class="flex flex-col">
  {#if label}
    <label class="block text-gray-700 font-bold mb-1 uppercase text-sm">
      {label}
      {#if required}
        <span class="text-red-500">*</span>
      {/if}
    </label>
  {/if}
  <textarea
    {id}
    {name}
    {value}
    {placeholder}
    {required}
    {rows}
    on:change
    on:keyup
    class:mb-8={isFormField}
    class:border-red-300={hasError}
    class={classes} />
</div>
