// src/routes/PlateDetails/components/TodoList.svelte
<script>
  import Checkbox from '../../../components/Checkbox.svelte';
  import plateStore from '../../../store/plate';

  export let todos;
  export let plateId;

  let newTodos = todos;

  const toggleCompleted = id => {
    const index = newTodos.findIndex(todo => todo.id === id);
    newTodos[index].completed = !newTodos[index].completed;

    plateStore.updatePlate({
      id: plateId,
      todos: newTodos,
    });
  };
</script>

{#if todos.length > 0}
  <div class="bg-white rounded-lg shadow p-4">
    <h3 class="text-xl font-bold text-gray-700 mb-2 uppercase">Todos</h3>
    <ul class="mt-2 p-2">
      {#each newTodos as todo}
        <li class="mb-4 flex justify-between items-center">
          <div class="flex items-center">
            <span
              class:line-through={todo.completed}
              class="text-gray-700 text-xl">
              {todo.title}
            </span>
          </div>
          <Checkbox
            checked={todo.completed}
            on:click={() => toggleCompleted(todo.id)} />
        </li>
        <hr class="pb-2 mb-2" />
      {/each}
    </ul>
  </div>
{/if}

// src/views/TodoList/TodoList.vue
<template>
  <div>
    <div class="p-4">
      <h1 class="mb-4">{{ todoList.title }}</h1>
      <h3 class="text-dark">{{ todoList.description }}</h3>
    </div>
    <div class="flex flex-row flex-wrap">
      <div
        v-for="todo in todoList.todos"
        :key="todo.id"
        class="bg-white shadow rounded w-full sm:w-full md:w-1/4 lg:w-1/5 m-2 sm:m-2 lg:m-4 p-4 flex-grow"
      >
        <div class="flex justify-between items-center">
          <div class="flex flex-col">
            <div class="text-xl font-bold">{{ todo.title }}</div>
            <div>{{ todo.description }}</div>
          </div>
          <font-awesome-icon
            icon="check-circle"
            :class="todo.completed ? 'text-green' : 'text-grey-darker'"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from 'vuex'
import DefaultLayout from '@/components/DefaultLayout'
export default {
  async created() {
    this.$emit('update:layout', DefaultLayout)
    await this.$store.dispatch('todoList/getTodoList', this.$route.params.id)
  },
  computed: mapState('todoList', ['todoList'])
}
</script>
