// src/router/Router.svelte
<script>
  import { Router } from 'svelte-routing'

  import CreatePlate from '../views/CreatePlate/CreatePlate'
  import Dashboard from '../views/Dashboard/Dashboard'
  import Login from '../views/Login/Login'

  import DefaultLayoutRoute from './components/DefaultLayoutRoute'
</script>

<Router url="">
  <DefaultLayoutRoute path="/" component={Dashboard} />
  <DefaultLayoutRoute path="create-plate" component={CreatePlate} />
  <DefaultLayoutRoute path="login" component={Login} />
</Router>

// src/router/index.tsx
import { Switch } from 'react-router-dom'
import React from 'react'

import { Login } from '../views/Login/Login'
import { Dashboard } from '../views/Dashboard/Dashboard'

import { DefaultLayoutRoute } from './components/DefaultLayoutRoute'
import { SimpleLayoutRoute } from './components/SimpleLayoutRoute'

export function Router() {
  return (
    <Switch>
      <SimpleLayoutRoute exact path="/" component={Login} />
      <DefaultLayoutRoute exact path="/dashboard" component={Dashboard} />
    </Switch>
  )
}
