// src/views/Register/Register.vue
<template>
  <div
    class="h-full flex items-center flex-col justify-center bg-blue-darker p-4"
  >
    <form
      @submit.prevent="handleSubmit"
      class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 w-full sm:w-full md:w-1/2 lg:w-1/3"
    >
      <div class="flex justify-between items-center flex-row w-full mb-4">
        <div class="text-2xl">Register</div>
        <div class="text-2xl">🍛</div>
      </div>
      <div class="mb-4">
        <TextField
          type="text"
          name="firstName"
          placeholder="First Name"
          label="First Name"
          v-model="firstName"
          v-validate="'required'"
          :hasErrors="errors.has('firstName')"
          :errorMessage="errors.first('firstName')"
        />
      </div>
      <div class="mb-4">
        <TextField
          type="text"
          name="lastName"
          placeholder="Last Name"
          label="Last Name"
          v-model="lastName"
          v-validate="'required'"
          :hasErrors="errors.has('lastName')"
          :errorMessage="errors.first('lastName')"
        />
      </div>
      <div class="mb-4">
        <TextField
          type="email"
          name="email"
          placeholder="Email"
          label="Email"
          v-model="email"
          v-validate="'required|email'"
          :hasErrors="errors.has('email')"
          :errorMessage="errors.first('email')"
        />
      </div>
      <div class="mb-6">
        <TextField
          type="password"
          name="password"
          placeholder="******************"
          label="Password"
          v-model="password"
          v-validate="'required'"
          :hasErrors="errors.has('password')"
          :errorMessage="errors.first('password')"
        />
      </div>
      <button
        class="bg-teal w-full hover:bg-teal-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mb-4"
        type="submit"
      >
        Register
      </button>
    </form>
  </div>
</template>

<script>
import BasicLayout from '@/components/BasicLayout'
import TextField from '@/components/TextField'

export default {
  components: {
    TextField
  },
  data: () => ({
    firstName: '',
    lastName: '',
    email: '',
    password: ''
  }),
  created() {
    this.$emit('update:layout', BasicLayout)
  },
  methods: {
    handleSubmit() {
      this.$validator.validateAll().then(async result => {
        if (!result) {
          return
        }

        const payload = {
          firstName: this.firstName,
          lastName: this.lastName,
          email: this.email,
          password: this.password
        }

        await this.$store.dispatch('auth/register', payload)
        this.$router.push('/dashboard')
      })
    }
  }
}
</script>

// src/routes/Register/index.svelte
<script>
  import page from 'page';

  import Input from '../../components/Input.svelte';
  import Button from '../../components/Button.svelte';
  import { register } from '../../store/auth';

  const formValues = {
    email: '',
    password: '',
  };

  const handleChange = e => {
    formValues[e.target.name] = e.target.value;
  };

  const handleSubmit = async () => {
    await register(formValues);
    page('/');
  };
</script>

<div class="w-full h-full flex items-center justify-center p-4">
  <form
    on:submit|preventDefault={handleSubmit}
    class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 w-full md:w-3/4
    lg:w-1/2 xl:w-1/3">
    <h1 class="text-3xl text-gray-800 mb-4 font-bold">Register</h1>
    <Input
      name="email"
      type="email"
      label="Email"
      isFormField
      placeholder="email address"
      on:change={handleChange}
      value={formValues.email} />
    <Input
      name="password"
      type="password"
      label="Password"
      isFormField
      placeholder="password"
      on:change={handleChange}
      value={formValues.password} />
    <Button type="submit" fullWidth>Register</Button>
  </form>
</div>
