// src/components/Button.vue
<template>
  <button
    :type="type"
    class="text-grey-darkest font-bold py-2 px-4 rounded inline-flex items-center focus:outline-none text-grey-lightest"
    :class="colorClass + ' ' + widthClasses"
    @click="$emit('onClick')"
  >
    <font-awesome-icon v-if="icon" class="mr-2" :icon="icon" />
    <span>{{ text }}</span>
  </button>
</template>

<script>
export default {
  props: {
    type: String,
    text: String,
    color: String,
    icon: String,
    fullWidth: Boolean
  },
  computed: {
    colorClass() {
      if (this.color) {
        return `bg-${this.color} hover:bg-${this.color}-dark`
      } else {
        return 'bg-grey hover:bg-grey-dark'
      }
    },
    widthClasses() {
      if (this.fullWidth) {
        return 'w-full justify-center'
      } else {
        return ''
      }
    }
  }
}
</script>

// src/components/Button.svelte
<script>
  export let fullWidth = false;
  export let type = 'button';
  export let loading = false;

  let classes = '';

  $: classes =
    'rounded py-3 bg-gray-700 hover:bg-gray-800 text-lg uppercase xl:text-base text-white flex justify-center items-center flex-row font-semibold leading-tight shadow-md ' +
    ($$props.class ? $$props.class : '');
</script>

<button
  {type}
  on:click
  class:w-full={fullWidth}
  class:px-2={!fullWidth}
  class={classes}
  class:px-4={!fullWidth}
  class:md:px-5={!fullWidth}
  class:xl:px-4={!fullWidth}>
  {#if loading}
    <div class="spinner" />
  {:else}
    <slot />
  {/if}
</button>
