// src/components/TextField.vue
<template>
  <div>
    <label
      class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2"
      v-if="label"
    >
      {{ label }}
    </label>
    <input
      :type="type"
      :name="name"
      :id="id"
      :placeholder="placeholder"
      @input="$emit('input', $event.target.value)"
      class="appearance-none block w-full bg-white text-grey-darker border-2 rounded py-3 px-4 mb-1 leading-tight focus:outline-none"
      :class="{
        'border-2 border-red-light': hasErrors,
        'text-2xl md:text-3xl': isLarge
      }"
    />
    <span class="text-sm text-red-light" v-if="errorMessage">{{
      errorMessage
    }}</span>
  </div>
</template>

<script>
export default {
  props: {
    label: String,
    type: String,
    name: String,
    id: String,
    isLarge: Boolean,
    placeholder: String,
    hasErrors: Boolean,
    errorMessage: String
  },
  $_veeValidate: {
    value() {
      return this.$el.value
    },
    name() {
      return this.name
    }
  }
}
</script>

// src/components/TextField.svelte
<script>
  export let label = undefined;
  export let textFieldValue = '';
  export let name = '';
  export let isFormField = false;
  export let fullWidth = false;
  export let placeholder = '';
  export let required = false;
</script>

<div class:w-full={fullWidth} class="flex flex-col">
  {#if label}
    <label class="block text-gray-700 font-bold mb-1 uppercase text-sm">
      {label}
      {#if required}
        <span class="text-red-500">*</span>
      {/if}
    </label>
  {/if}
  <input
    {name}
    {placeholder}
    {required}
    type="text"
    bind:value={textFieldValue}
    class:w-full={fullWidth}
    class:mb-8={isFormField}
    class="block appearance-none w-full bg-white border-2 border-gray-400
    hover:border-gray-500 px-4 py-3 pr-8 rounded leading-tight
    focus:outline-none focus:shadow-outline" />
</div>
