// src/components/Textarea/index.svelte
<script>
  export let label = '';
  export let name = '';
  export let isFormField = false;
  export let rows = 5;
  export let value;
</script>

<div class="flex flex-col">
  <label class="block text-gray-700 font-bold mb-1 uppercase text-sm">
    {label}
  </label>
  <textarea
    {name}
    {rows}
    {value}
    on:change
    on:keyup
    class="block appearance-none bg-white border-2 border-gray-400
    hover:border-gray-500 px-4 py-3 pr-8 rounded leading-tight
    focus:outline-none focus:shadow-outline"
    class:mb-8={isFormField} />
</div>

// src/components/TextArea.vue
<template>
  <div>
    <label
      class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2"
      v-if="label"
    >
      {{ label }}
    </label>
    <textarea
      :name="name"
      :id="id"
      rows="4"
      :placeholder="placeholder"
      @input="$emit('input', $event.target.value)"
      class="appearance-none block w-full bg-white text-grey-darker border-2 rounded py-3 px-4 mb-1 leading-tight focus:outline-none"
      :class="hasErrors ? 'border-2 border-red-light' : ''"
    />
    <span class="text-sm text-red-light" v-if="errorMessage">{{
      errorMessage
    }}</span>
  </div>
</template>

<script>
export default {
  props: {
    label: String,
    name: String,
    id: String,
    placeholder: String,
    hasErrors: Boolean,
    errorMessage: String
  },
  $_veeValidate: {
    value() {
      return this.$el.value
    },
    name() {
      return this.name
    }
  }
}
</script>
