// src/views/TodoList/TodoList.vue
<template>
  <div>
    <div class="p-4">
      <h1 class="mb-4">{{ todoList.title }}</h1>
      <h3 class="text-dark">{{ todoList.description }}</h3>
    </div>
    <div class="flex flex-row flex-wrap">
      <div
        v-for="todo in todoList.todos"
        :key="todo.id"
        class="bg-white shadow rounded w-full sm:w-full md:w-1/4 lg:w-1/5 m-2 sm:m-2 lg:m-4 p-4 flex-grow"
      >
        <div class="flex justify-between items-center">
          <div class="flex flex-col">
            <div class="text-xl font-bold">{{ todo.name }}</div>
            <div>{{ todo.description }}</div>
          </div>
          <font-awesome-icon
            icon="check-circle"
            :class="todo.completed ? 'text-green' : 'text-grey-darker'"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from 'vuex'

import DefaultLayout from '@/components/DefaultLayout'

export default {
  created() {
    this.$emit('update:layout', DefaultLayout)
  },
  mounted() {
    this.$store.dispatch('getTodoList', this.$route.params.id)
  },
  computed: mapState(['todoList'])
}
</script>

// src/components/TodoList.svelte
<script>
  import { faPlus } from '@fortawesome/free-solid-svg-icons/faPlus';
  import { createEventDispatcher } from 'svelte';

  import Input from './Input';
  import Icon from './Icon';

  const dispatch = createEventDispatcher();

  export let todos;

  console.log(todos)
</script>

<div class="flex flex-col p-4 rounded shadow bg-white">
  <div class="flex justify-between items-center flex-row mb-4">
    <div class="text-2xl font-bold">Todos</div>
    <Icon
      class="cursor-pointer"
      fill="#4a5568"
      icon={faPlus}
      height="1.5rem"
      width="1.5rem"
      on:click={() => dispatch('addTodo', { title: 'new todo' })} />
  </div>
  <Input
    name="todoItem"
    type="text"
    isFormField
    placeholder="todo item"
    value={''} />
  <hr />
  {#each todos as todo}
    <div>{todo.title}</div>
  {/each}
</div>
