// src/components/App/index.tsx
import React, { useEffect } from 'react';
import { BrowserRouter } from 'react-router-dom';

import { ThemeProvider } from '../../context/theme';
import { Routes } from '../../routes';

export const App: React.FC = () => {
  useEffect(() => {
    if (import.meta.env.MODE === 'production') {
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', () => {
          navigator.serviceWorker.register('/sw.js').then().catch();
        });
      }
    }
  }, []);

  return (
    <BrowserRouter>
      <ThemeProvider>
        <Routes />
      </ThemeProvider>
    </BrowserRouter>
  );
};

// src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { Router } from 'svelte-router-spa';

  import Loader from './components/Loader/Loader';
  import { firebaseUser } from './store/firebase';
  import { routes } from './routes/routes';
  import {
    initializeFirebase,
    firebaseConfig,
    firebaseLoading,
  } from './store/firebase';

  onMount(() => {
    initializeFirebase();

    if (process.env.NODE_ENV === 'production') {
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', () => {
          navigator.serviceWorker
            .register('/sw.js')
            .then()
            .catch();
        });
      }
    }
  });
</script>

{#if $firebaseLoading}
  <Loader fullPage />
{:else}
  <Router {routes} />
{/if}
