// src/routes/Login/index.svelte
<script>
  import Input from '../../components/Input';
  import Button from '../../components/Button';
  import { auth } from '../../store/auth';

  const formValues = {
    email: '',
    password: '',
  };

  const handleChange = e => {
    formValues[e.target.name] = e.target.value;
  };

  const handleSubmit = () => {
    $auth
      .login(formValues.email, formValues.password)
      .then(response => {
        console.log('Success! Response: ' + JSON.stringify({ response }), form);
      })
      .catch(error => console.log('Failed :( ' + JSON.stringify(error), form));
  };
</script>

<div class="w-full h-full flex items-center justify-center p-4">
  <form
    class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 w-full md:w-3/4
    lg:w-1/3 xl:w-1/4">
    <h1 class="text-3xl text-gray-800 mb-4 font-bold">Login</h1>
    <Input
      name="email"
      type="email"
      label="Email"
      isFormField
      placeholder="email address" />
    <Input
      name="password"
      type="password"
      label="Password"
      isFormField
      placeholder="password" />
    <Button type="submit" fullWidth>Login</Button>
  </form>
</div>

// src/views/Login/Login.vue
<template>
  <div class="h-full flex items-center justify-center bg-blue-darker p-4">
    <form
      @submit.prevent="handleSubmit"
      class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 w-full sm:w-full md:w-1/2 lg:w-1/3"
    >
      <div class="mb-4">
        <AppInput
          type="email"
          name="email"
          placeholder="Email"
          label="Email"
          v-model="email"
          validations="required|email"
        />
      </div>
      <div class="mb-6">
        <AppInput
          type="password"
          name="password"
          placeholder="******************"
          label="Password"
          v-model="password"
          validations="required"
        />
      </div>
      <div class="flex items-center justify-between">
        <button
          class="bg-teal w-full hover:bg-teal-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Login
        </button>
      </div>
    </form>
  </div>
</template>

<script>
import AppBasicLayout from '@/components/AppBasicLayout'
import AppInput from '@/components/AppInput'

export default {
  components: {
    AppInput
  },
  data: () => ({
    email: '',
    password: ''
  }),
  created() {
    this.$emit('update:layout', AppBasicLayout)
  },
  methods: {
    handleSubmit() {
      console.log(this.errors)
      this.$validator.validateAll().then(() => {
        const payload = {
          email: this.email,
          password: this.password
        }

        this.$store.dispatch('login', payload)
        this.$router.push('/dashboard')
      })
    }
  }
}
</script>
