// src/views/Login/index.vue
<template>
  <div
    class="h-full flex items-center flex-col justify-center bg-blue-darker p-4"
  >
    <form
      @submit.prevent="handleSubmit"
      class="bg-grey-light shadow-md px-8 pt-6 pb-8 mb-4 w-full sm:w-full md:w-1/2 lg:w-1/3 rounded"
    >
      <div class="flex justify-between items-center flex-row w-full mb-4">
        <div class="text-2xl">{{ $t('login') }}</div>
        <div class="text-2xl">🍛</div>
      </div>
      <div class="mb-4">
        <TextField
          type="email"
          name="email"
          placeholder="Email"
          label="Email"
          v-model="email"
          v-validate="'required|email'"
          :hasErrors="errors.has('email')"
          :errorMessage="errors.first('email')"
        />
      </div>
      <div class="mb-6">
        <TextField
          type="password"
          name="password"
          placeholder="******************"
          label="Password"
          v-model="password"
          v-validate="'required'"
          :hasErrors="errors.has('password')"
          :errorMessage="errors.first('password')"
        />
      </div>
      <button
        class="bg-teal-dark border-b-4 border-teal-darker rounded w-full hover:bg-teal-dark text-white font-bold py-2 px-4 focus:outline-none hover:bg-teal mb-4"
        type="submit"
      >
        {{ loading ? 'loading...' : 'Login' }}
      </button>
      <div @click="goToRegister()" class="cursor-pointer">
        Dont have an account?
      </div>
      <div class="text-red mt-4 uppercase" v-if="loginError">
        {{ loginError }}
      </div>
    </form>
  </div>
</template>

<script>
import { mapState } from 'vuex'
import BasicLayout from '@/components/BasicLayout'
import TextField from '@/components/TextField'

export default {
  components: {
    TextField
  },
  data() {
    return {
      email: '',
      password: '',
      loading: false
    }
  },
  computed: mapState('auth', ['loginError']),
  created() {
    this.$emit('update:layout', BasicLayout)
  },
  methods: {
    handleSubmit() {
      this.$validator.validateAll().then(async result => {
        if (!result) {
          return
        }

        const payload = {
          email: this.email,
          password: this.password
        }

        this.loading = true
        await this.$store.dispatch('auth/login', payload)
        this.loading = false

        this.$router.push({ name: 'dashboard' })
      })
    },
    goToRegister() {
      this.$router.push(`/${this.$i18n.locale}/register`)
    }
  }
}
</script>

// src/routes/Login/index.svelte
<script>
  import page from 'page';
  import { _ } from 'svelte-i18n';

  import authStore, { errorMessage } from '../../store/auth';
  import TextField from '../../components/TextField.svelte';
  import PasswordField from '../../components/PasswordField.svelte';
  import Button from '../../components/Button.svelte';
  import Meta from '../../components/Meta.svelte';

  let submitting = false;

  const formValues = {
    username: '',
    password: '',
  };

  const handleSubmit = async () => {
    submitting = true;
    await authStore.login(formValues);
    page('/');
    submitting = false;
  };
</script>

<Meta
  title="Login"
  description="Welcome to Plate, a place to manage your stuff, login now to get
  started" />

<div class="w-full h-full flex items-center justify-center p-4">
  <form
    on:submit|preventDefault={handleSubmit}
    class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 w-full md:w-3/4
    lg:w-1/2 xl:w-1/3">
    <h1 class="text-3xl text-gray-800 mb-4 font-bold">{$_('login.title')}</h1>
    <TextField
      name="username"
      label={$_('login.username')}
      isFormField
      required
      placeholder={$_('login.username')}
      bind:textFieldValue={formValues.username} />
    <PasswordField
      name="password"
      label={$_('login.password')}
      isFormField
      required
      placeholder={$_('login.password')}
      bind:passwordFieldValue={formValues.password} />
    <Button type="submit" fullWidth loading={submitting}>
      {$_('login.submitText')}
    </Button>
    {#if $errorMessage}
      <div class="mt-4 bg-red-500 rounded p-2 font-bold text-white text-xl">
        {$errorMessage}
      </div>
    {/if}
  </form>
</div>
